name: Ping Cron Monitor

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl https://cron-raels.vercel.app/api/check
